{"ast":null,"code":"var __extends = this && this.__extends || function () {\n  var _extendStatics = function extendStatics(d, b) {\n    _extendStatics = Object.setPrototypeOf || {\n      __proto__: []\n    } instanceof Array && function (d, b) {\n      d.__proto__ = b;\n    } || function (d, b) {\n      for (var p in b) {\n        if (b.hasOwnProperty(p)) d[p] = b[p];\n      }\n    };\n\n    return _extendStatics(d, b);\n  };\n\n  return function (d, b) {\n    _extendStatics(d, b);\n\n    function __() {\n      this.constructor = d;\n    }\n\n    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());\n  };\n}(); // See https://stackoverflow.com/questions/30402287/extended-errors-do-not-have-message-or-stack-trace\n\n\nvar NaviError =\n/** @class */\nfunction (_super) {\n  __extends(NaviError, _super);\n\n  function NaviError(message) {\n    var _newTarget = this.constructor;\n\n    var _this = this;\n\n    var trueProto = _newTarget.prototype;\n    _this = _super.call(this, message) || this;\n    _this.__proto__ = trueProto;\n    if (Error.hasOwnProperty('captureStackTrace')) Error.captureStackTrace(_this, _this.constructor);else Object.defineProperty(_this, 'stack', {\n      value: new Error().stack\n    });\n    Object.defineProperty(_this, 'message', {\n      value: message\n    });\n    return _this;\n  }\n\n  return NaviError;\n}(Error);\n\nexport { NaviError };\n\nvar NotFoundError =\n/** @class */\nfunction (_super) {\n  __extends(NotFoundError, _super);\n\n  function NotFoundError(pathname) {\n    var _this = _super.call(this, \"URL not found: \" + pathname) || this; // If you create a NotFoundError without a pathname, the\n    // resolver will catch it and assign the correct pathname.\n\n\n    _this.pathname = pathname;\n    _this.status = 404;\n    _this.name = 'NotFoundError';\n    return _this;\n  }\n\n  return NotFoundError;\n}(NaviError);\n\nexport { NotFoundError };\n\nvar OutOfRootError =\n/** @class */\nfunction (_super) {\n  __extends(OutOfRootError, _super);\n\n  function OutOfRootError(url) {\n    var _this = _super.call(this, \"URL not managed by router: \" + url.href) || this;\n\n    _this.url = url;\n    _this.name = 'OutOfRootError';\n    return _this;\n  }\n\n  return OutOfRootError;\n}(NaviError);\n\nexport { OutOfRootError };","map":null,"metadata":{},"sourceType":"module"}